<?php

namespace TracabiliteBundle\Repository;

/**
 * SaisiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisiRepository extends \Doctrine\ORM\EntityRepository
{
}
