security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CLIENT:      ROLE_USER
        ROLE_PRODUCTEUR:  ROLE_USER
        ROLE_EXPORTATEUR: ROLE_USER
        ROLE_CONTROLEUR:  ROLE_USER
        ROLE_DPV:         ROLE_USER
        ROLE_INSPECTEUR:  ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_PRODUCTEUR,ROLE_EXPORTATEUR,ROLE_CONTROLEUR,ROLE_CLIENT,ROLE_INSPECTEUR]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                success_handler: redirect.after.login
                always_use_default_target_path: false
                default_target_path:            /home
                target_path_parameter:          _target_path
                use_referer:                    false
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/confirmed, role: ROLE_GERANT }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/caissier, role: ROLE_ADMIN }
        - { path: ^/smart, role: ROLE_ADMIN }
        - { path: ^/produit, role: ROLE_ADMIN }
        - { path: ^/personne/new, role: ROLE_ADMIN }
        - { path: ^/dpv/, role: ROLE_ADMIN }
        - { path: ^/producteur/, role: ROLE_PRODUCTEUR }
        - { path: ^/campagne/, role: [ROLE_PRODUCTEUR, ROLE_EXPORTATEUR] }
        - { path: ^/lot/, role: [ROLE_PRODUCTEUR, ROLE_EXPORTATEUR] }
        - { path: ^/registrepalettisation, role: ROLE_DPV }