tracabilite:
    resource: "@TracabiliteBundle/Resources/config/routing.yml"
    prefix:   /

tuto_personne:
    resource: "@TutoBundle/Controller/PersonneController.php"
    type:     annotation

tuto:
    resource: "@TutoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

