<?php

namespace TpaBundle\Repository;

/**
 * CalendrierProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierProductionRepository extends \Doctrine\ORM\EntityRepository
{
}
