<?php

namespace TpaBundle\Repository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeInspectionRepository extends \Doctrine\ORM\EntityRepository
{
}
