<?php

namespace TpaBundle\Repository;

/**
 * ficheOperateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ficheOperateurRepository extends \Doctrine\ORM\EntityRepository
{
}
