<?php

namespace TpaBundle\Repository;

/**
 * gestionQualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gestionQualiteRepository extends \Doctrine\ORM\EntityRepository
{
}
