<?php

namespace TpaBundle\Repository;

/**
 * SiteConditionnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteConditionnementRepository extends \Doctrine\ORM\EntityRepository
{
}
