<?php

namespace TpaBundle\Repository;

/**
 * SiteProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteProductionRepository extends \Doctrine\ORM\EntityRepository
{
}
